### ISSUE TITLE
Remove .git and .vs dir

### ISSUE THREAD

**Issue by zibul444** [szkiba/xk6-prometheus#11]
Hi. This is an amazing project, thank you so much. Can I advise you to delete personal files from the repository?
.github
.vscode

**Comment by szkiba** [comment]
Hi @zibul444 , .github contains GitHub workflow config so it should be there. The .vscode contains only linter config for potential contributors...

**Comment by zibul444** [comment]
OK, well, then you can close, apparently I don't know
